elasticsearch:
  url: http://trendtf22.osl.tib.eu:9200
  index: dtf_fulltext

flask:
  host: trendtf23.osl.tib.eu
  port: 8124
  debug: False
  template_folder: /mnt/drive/scripts/TrendtfSearch/templates
  https_host: service.tib.eu
  application_root: trendtfsearch

results_per_page: 10
