---
- name: install dependencies
  hosts: my_debian_servers
  become: true
  vars_files:
    - vars.yml
  tasks:
    - name: Update package cache
      become: true
      apt:
        update_cache: yes
      ignore_errors: yes

    - name: Check if python3 is installed, if not install it
      become: true
      raw: python3 --version
      register: python_check
      ignore_errors: yes
      changed_when: false

    - name: Install python3 if not installed
      become: true
      apt:
        name: python3
        state: present
      when: python_check.rc != 0

    - name: Check if pip3 is installed. if not install it
      become: true
      raw: pip3 --version
      register: pip_check
      ignore_errors: yes
      changed_when: false

    - name: Install pip3 if not installed
      become: true
      apt:
        name: python3-pip
        state: present
      when: pip_check.rc != 0


    - name: Install pyyaml if not installed
      pip:
        name: pyyaml
        executable: pip3
        state: present
        extra_args: --upgrade
      vars:
        ansible_python_interpreter: /usr/bin/python3
   

    - name: Install pika if not installed
      pip:
        name: pika
        executable: pip3
        state: present
        extra_args: --upgrade
      vars:
        ansible_python_interpreter: /usr/bin/python3

    - name: Install Screen
      apt:
        name: screen
        state: present


  